Repository mitre/mitre-saf, pull requests merged in 2020-07, with the labels that each got.

#100 fixed #99
  src/assets/data/resources.json
Labels: bug

#112 Update communityData.json
  src/assets/data/communityData.json
Labels: bug, documentation

#97 added lifecycle graphic to homepage
  public/How to Use the MITRE SAF.pdf
  public/MITRE_SAF_Code_Review_Recommendations.pdf
  src/assets/data/communityData.json
  src/assets/data/faqs.json
  src/assets/data/resources.json
  src/assets/data/whatWeDo.json
  src/assets/img/tools/inspec-runner.png
  src/assets/img/what-we-do/toolchain.png
  src/assets/img/what-we-do/whenToUseIt.png
  src/components/About/aboutCommunity.vue
  src/components/Team/TeamHeader.vue
  src/components/common/partners.vue
  src/components/core/Footer.vue
  src/components/home/dem.vue
  src/components/home/whatwedo.vue
  src/components/home/wwdComponents/wwdBasicCard.vue
  src/components/home/wwdComponents/wwdSection.vue
  src/views/ControlTableView.vue
  src/views/Validation.vue
Labels: documentation, enhancement
